export const locales = [
    "en_GB",
    "cat_CAT",
    "nn_NO",
    "nb_NO",
    "ar_AR",
    "es_AR",
    "fi_FI",
    "hu_HU",
    "nl_NL",
    "tr_TR",
    "it_IT",
    "it_IT (PinoLG01)",
    "kw_KW",
    "fa_IR",
    "fr_FR",
    "sv_SE",
    "th_TH",
    "es_ES",
    "ru_RU",
    "pt_BR",
    "de_DE",
    "pt_PT",
    "pl_PL",
    "pl_PL (Charles)",
    "zh_TW",
    "ja_JA",
    "fil_PH",
    "zh_CN",
    "zh_CN (Anlijie)",
    "he_IL",
    "vi_VI",
    "kv_KV",
    "sl_SI",
    "uk_UA (Imze)",
    "uk_UA",
    "zh_HK",
];