name: Deploy to github pages
on:
  push:
      branches:
        - main
jobs:
  deploy:
    name: Deploying to gh pages
    runs-on: ubuntu-latest
    steps:
      -name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

      -name: Checkout branch
      uses: actions/checkout@v3

      -name: Clean install dependencies
      run: npm ci

      -name: Deploy
      run:
        git config user.name "WellingtonWritesCode" && git config user.email "17155519+WellingtonWritesCode@users.noreply.github.com"
        npm run deploy
